modLoader="javafml"
loaderVersion="[28,)"
# issueTrackerURL=""

[[mods]]
modId="shuffle"
version="${file.jarVersion}"
displayName="Shuffle"
#updateJSONURL=""
displayURL="https://curseforge.com/minecraft/mc-mods/shuffle"
logoFile="assets/shuffle/icon.png"
credits="@Braden#5552 for commissioning the mod"
authors="Trikzon"
description='''
When toggled, after placing a block your hotbar switches to another slot which holds a block. This is useful for making builds with random blocks.
'''